### ISSUE TITLE
Multiple domains per certificate

### ISSUE THREAD

**Issue by Matt-Yorkley** [coopdevs/certbot_nginx#4]
Hi coopdevs, we've encountered a need to declare multiple domains per certificate with OFN, for example for `openfoodfrance.org` and `www.openfoodfrance.org`, but potentially others as well.

It's easy to do (the command to create a certificate can take multiple domain arguments), but it means supplying a new variable or list of additional domains/subdomains and adding them into the command conditionally.

What do you think? I could submit a PR here to make the change, or we could fork this repo for ofn-install.

**Comment by elf-pavlik** [comment]
Maybe instead of `domain_name` with single string value, it could take ` domain_names` with an array. Actually probably it could accept either one and if `domain_names` stays undefined but it has `domain_name` defined it could set `domain_names` to array with one item using [`set_fact` module](https://docs.ansible.com/ansible/latest/modules/set_fact_module.html)

**Comment by Matt-Yorkley** [comment]
Yeah, it looks like we can just do it from within ofn-install, so no need to update this repo:

https://github.com/openfoodfoundation/ofn-install/pull/236
